name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: pdftool/pdftool.csproj
      TEST_PROJECT_PATH: pdftool.Tests/pdftool.Tests.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore win-x64
        run: dotnet restore $PROJECT_PATH -r win-x64

      - name: Restore linux-x64
        run: dotnet restore $PROJECT_PATH -r linux-x64

      - name: Build (Release)
        run: dotnet build $PROJECT_PATH --configuration Release --no-restore

      - name: Run Tests (with TRX)
        run: dotnet test $TEST_PROJECT_PATH --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "**/test-results.trx"
